# -*- coding: utf-8 -*-
"""Docgenie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZPUrIplLZFgwa_GsvMCuRDNbsLVSWRz
"""

!pip uninstall -y gradio transformers
!pip install gradio transformers --upgrade

import ast
import gradio as gr
from transformers import pipeline
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
import datetime
import os

!pip install --upgrade transformers

from transformers import pipeline

generator = pipeline(
    task="text-generation",
    model="google/flan-t5-base"
)

result = generator("What is AI?", max_length=50)
print(result)

class DocGenieAnalyzer:

    @staticmethod
    def extract_function_signature(code):
        tree = ast.parse(code)
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                return node
        return None

    @staticmethod
    def analyze_function_logic(func_node):
        analysis = {
            "has_loops": False,
            "has_conditions": False,
            "has_return": False
        }

        for node in ast.walk(func_node):
            if isinstance(node, (ast.For, ast.While)):
                analysis["has_loops"] = True
            if isinstance(node, ast.If):
                analysis["has_conditions"] = True
            if isinstance(node, ast.Return):
                analysis["has_return"] = True

        return analysis

def generate_ai_docstring(code, style):
    prompt = f"""
Generate a professional {style} style Python docstring
for the following function:

{code}

Docstring:
"""

    result = generator(prompt, max_length=300, do_sample=False)
    return result[0]["generated_text"]

def process_code(code, style):
    try:
        func_node = DocGenieAnalyzer.extract_function_signature(code)
        if not func_node:
            return "No function detected."

        analysis = DocGenieAnalyzer.analyze_function_logic(func_node)

        docstring = generate_ai_docstring(code, style)

        lines = code.split("\n")
        indent = " " * 4
        formatted_doc = indent + docstring.replace("\n", "\n" + indent)

        lines.insert(1, formatted_doc)

        return "\n".join(lines)

    except Exception as e:
        return f"Error: {str(e)}"

def generate_pdf(output_code):
    filename = "DocGenie_Report.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>Doc-Genie Documentation Report</b>", styles["Title"]))
    elements.append(Spacer(1, 12))
    elements.append(Preformatted(output_code, styles["Code"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Generated on: {datetime.datetime.now()}", styles["Normal"]))

    doc.build(elements)

    return filename

with gr.Blocks(title="Doc-Genie AI") as demo:

    gr.Markdown("# 📘 Doc-Genie\nAI Powered Python Docstring Generator")

    with gr.Row():
        with gr.Column():
            code_input = gr.Code(label="Enter Python Function", language="python")
            style_selector = gr.Radio(
                ["Google", "NumPy"],
                value="Google",
                label="Docstring Style"
            )
            generate_btn = gr.Button("Generate Docstring")

        with gr.Column():
            output_code = gr.Code(label="Output", language="python")
            pdf_btn = gr.Button("Download PDF")
            pdf_output = gr.File()

    generate_btn.click(
        process_code,
        inputs=[code_input, style_selector],
        outputs=output_code
    )

    pdf_btn.click(
        generate_pdf,
        inputs=output_code,
        outputs=pdf_output
    )

demo.launch()

def calculate_factorial(n: int) -> int:
    if n == 0:
        return 1
    return n * calculate_factorial(n-1)